"""Math-style helpers for Concrete FHE circuits.

The functions in this subpackage use bounded integer domains. Some operations
compile as native Concrete arithmetic, while others use lookup tables over the
declared domain.
"""

from ._lookup import FHECostWarning, LookupCost, LookupResourceError, estimate_lookup_cost
from ._operation import BoundedOperation
from .basic import (
    add,
    compile_fdim,
    compile_fma,
    compile_ldexp,
    compile_remainder,
    compile_scalbn,
    fma,
    make_fdim,
    make_ldexp,
    make_remainder,
    make_scalbn,
    compile_abs,
    compile_abs_diff,
    compile_absolute,
    compile_add,
    compile_clamp,
    compile_copysign,
    compile_cube,
    compile_divmod,
    compile_equal,
    compile_greater,
    compile_greater_equal,
    compile_is_close,
    compile_is_zero,
    compile_less,
    compile_less_equal,
    compile_maximum,
    compile_minimum,
    compile_modulo,
    compile_multiply,
    compile_negate,
    compile_not_equal,
    compile_saturating_add,
    compile_saturating_multiply,
    compile_saturating_subtract,
    compile_scalar_mul,
    compile_scalar_multiply,
    compile_select,
    compile_square,
    compile_sub,
    compile_subtract,
    cube,
    equal,
    greater,
    greater_equal,
    is_zero,
    less,
    less_equal,
    make_abs,
    make_abs_diff,
    make_absolute,
    make_clamp,
    make_copysign,
    make_divmod,
    make_is_close,
    make_modulo,
    make_saturating_add,
    make_saturating_multiply,
    make_saturating_subtract,
    make_scalar_multiply,
    maximum,
    minimum,
    multiply,
    negate,
    not_equal,
    select,
    square,
    subtract,
)
from .binary_division import (
    compile_fixed_point_divide,
    compile_unsigned_floor_divide,
    compile_unsigned_mod,
    fixed_point_divide_bits,
    make_fixed_point_divide,
    make_unsigned_floor_divide,
    make_unsigned_mod,
    unsigned_divide_bits,
    unsigned_mod_bits,
)
from .bits import (
    BIT_AND_LUT,
    BIT_NOT_LUT,
    BIT_OR_LUT,
    BIT_SELECT_LUT,
    BIT_XOR_LUT,
    FULL_ADDER_CARRY_LUT,
    FULL_ADDER_SUM_LUT,
    FULL_SUBTRACTOR_BORROW_LUT,
    FULL_SUBTRACTOR_DIFF_LUT,
    band,
    bit_and,
    bit_and_many,
    bit_length_bits,
    bit_not,
    bit_op_many,
    bit_or,
    bit_or_many,
    bit_select,
    bit_xor,
    bit_xor_many,
    bits_to_unsigned,
    bnot,
    bor,
    bsel,
    bxor,
    fadd_bit,
    fsub_bit,
    full_adder_bit,
    full_subtractor_bit,
    integer_to_bits,
    multiply_bits,
    parity_bits,
    popcount_bits,
    rotate_left_bits,
    rotate_right_bits,
    shift_left_bits,
    shift_right_bits,
    sign_magnitude_to_twos_complement_bits,
    twos_complement_add_bits,
    twos_complement_bits,
    twos_complement_multiply_by_constant_bits,
    unsigned_compare_bits,
    unsigned_to_bits,
)
from .combinatorics import (
    compile_comb,
    compile_combinations,
    compile_exponential,
    compile_factorial,
    compile_fibonacci,
    compile_perm,
    compile_permutations,
    compile_power,
    compile_powmod,
    make_comb,
    make_combinations,
    make_exponential,
    make_factorial,
    make_fibonacci,
    make_perm,
    make_permutations,
    make_power,
    make_powmod,
)
from .fixed_point import (
    compile_ceil,
    compile_fixed_point_multiply,
    compile_floor,
    compile_floor_ceil,
    compile_modf,
    compile_rescale,
    compile_round,
    compile_round_to_multiple,
    compile_trunc,
    decode_fixed_point,
    encode_fixed_point,
    make_ceil,
    make_fixed_point_multiply,
    make_floor,
    make_floor_ceil,
    make_modf,
    make_rescale,
    make_round,
    make_round_to_multiple,
    make_trunc,
)
from .number_theory import (
    compile_gcd,
    compile_ilogb,
    make_ilogb,
    compile_hypot,
    compile_is_coprime,
    compile_is_divisible,
    compile_is_even,
    compile_is_odd,
    compile_is_prime,
    compile_isqrt,
    compile_lcm,
    compile_mod_inverse,
    compile_next_prime,
    compile_totient,
    make_gcd,
    make_hypot,
    make_is_coprime,
    make_is_divisible,
    make_is_even,
    make_is_odd,
    make_is_prime,
    make_isqrt,
    make_lcm,
    make_mod_inverse,
    make_next_prime,
    make_totient,
)
from .special import (
    compile_acos,
    compile_acosh,
    compile_asinh,
    compile_atanh,
    compile_exp2,
    make_acosh,
    make_asinh,
    make_atanh,
    make_exp2,
    compile_asin,
    compile_atan,
    compile_atan2,
    compile_cbrt,
    compile_cos,
    compile_cosh,
    compile_degrees,
    compile_erf,
    compile_erfc,
    compile_exp,
    compile_expm1,
    compile_gamma,
    compile_lgamma,
    compile_log,
    compile_log1p,
    compile_log2,
    compile_log10,
    compile_radians,
    compile_sigmoid,
    compile_sin,
    compile_sinh,
    compile_sqrt,
    compile_tan,
    compile_tanh,
    make_acos,
    make_asin,
    make_atan,
    make_atan2,
    make_cbrt,
    make_cos,
    make_cosh,
    make_degrees,
    make_erf,
    make_erfc,
    make_exp,
    make_expm1,
    make_gamma,
    make_lgamma,
    make_log,
    make_log1p,
    make_log2,
    make_log10,
    make_radians,
    make_sigmoid,
    make_sin,
    make_sinh,
    make_sqrt,
    make_tan,
    make_tanh,
)

absolute = BoundedOperation(
    "absolute",
    make_absolute,
    compile_absolute,
    description="Bounded encrypted absolute value.",
)
abs = absolute
clamp = BoundedOperation(
    "clamp",
    make_clamp,
    compile_clamp,
    description="Bounded encrypted clamp.",
)
modulo = BoundedOperation(
    "modulo",
    make_modulo,
    compile_modulo,
    description="Bounded encrypted modulo with explicit zero-denominator behavior.",
)
divmod = BoundedOperation(
    "divmod",
    make_divmod,
    compile_divmod,
    description="Bounded encrypted quotient and remainder.",
)
is_close = BoundedOperation(
    "is_close",
    make_is_close,
    compile_is_close,
    description="Bounded encrypted integer closeness predicate.",
)
abs_diff = BoundedOperation(
    "abs_diff",
    make_abs_diff,
    compile_abs_diff,
    description="Bounded encrypted absolute difference |left - right|.",
)

factorial = BoundedOperation(
    "factorial",
    make_factorial,
    compile_factorial,
    description="Bounded encrypted factorial.",
)
fibonacci = BoundedOperation(
    "fibonacci",
    make_fibonacci,
    compile_fibonacci,
    description="Bounded encrypted Fibonacci sequence lookup.",
)
power = BoundedOperation(
    "power",
    make_power,
    compile_power,
    description="Public-base exponentiation with an encrypted exponent.",
)
comb = BoundedOperation(
    "comb",
    make_comb,
    compile_comb,
    description="Bounded encrypted combinations.",
)
combinations = comb
perm = BoundedOperation(
    "perm",
    make_perm,
    compile_perm,
    description="Bounded encrypted permutations.",
)
permutations = perm

gcd = BoundedOperation(
    "gcd",
    make_gcd,
    compile_gcd,
    description="Bounded encrypted greatest common divisor.",
)
lcm = BoundedOperation(
    "lcm",
    make_lcm,
    compile_lcm,
    description="Bounded encrypted least common multiple.",
)
is_coprime = BoundedOperation(
    "is_coprime",
    make_is_coprime,
    compile_is_coprime,
    description="Bounded encrypted coprime predicate.",
)
is_divisible = BoundedOperation(
    "is_divisible",
    make_is_divisible,
    compile_is_divisible,
    description="Bounded encrypted divisibility predicate.",
)
isqrt = BoundedOperation(
    "isqrt",
    make_isqrt,
    compile_isqrt,
    description="Bounded encrypted integer square root.",
)
is_even = BoundedOperation(
    "is_even",
    make_is_even,
    compile_is_even,
    description="Bounded encrypted even predicate.",
)
is_odd = BoundedOperation(
    "is_odd",
    make_is_odd,
    compile_is_odd,
    description="Bounded encrypted odd predicate.",
)
is_prime = BoundedOperation(
    "is_prime",
    make_is_prime,
    compile_is_prime,
    description="Bounded encrypted primality predicate.",
)
totient = BoundedOperation(
    "totient",
    make_totient,
    compile_totient,
    description="Bounded encrypted Euler totient.",
)
next_prime = BoundedOperation(
    "next_prime",
    make_next_prime,
    compile_next_prime,
    description="Bounded encrypted next-prime lookup.",
)
mod_inverse = BoundedOperation(
    "mod_inverse",
    make_mod_inverse,
    compile_mod_inverse,
    description="Bounded encrypted modular inverse with explicit invalid behavior.",
)
hypot = BoundedOperation(
    "hypot",
    make_hypot,
    compile_hypot,
    description="Bounded encrypted rounded hypotenuse.",
)

floor = BoundedOperation(
    "floor",
    make_floor,
    compile_floor,
    description="Bounded fixed-point floor.",
)
ceil = BoundedOperation(
    "ceil",
    make_ceil,
    compile_ceil,
    description="Bounded fixed-point ceil.",
)
trunc = BoundedOperation(
    "trunc",
    make_trunc,
    compile_trunc,
    description="Bounded fixed-point truncation toward zero.",
)
round = BoundedOperation(
    "round",
    make_round,
    compile_round,
    description="Bounded fixed-point rounding.",
)
floor_ceil = BoundedOperation(
    "floor_ceil",
    make_floor_ceil,
    compile_floor_ceil,
    description="Bounded fixed-point floor and ceil pair.",
)
rescale = BoundedOperation(
    "rescale",
    make_rescale,
    compile_rescale,
    description="Bounded fixed-point rescaling.",
)

sin = BoundedOperation("sin", make_sin, compile_sin, description="Bounded fixed-point sine.")
cos = BoundedOperation("cos", make_cos, compile_cos, description="Bounded fixed-point cosine.")
tan = BoundedOperation("tan", make_tan, compile_tan, description="Bounded fixed-point tangent.")
asin = BoundedOperation("asin", make_asin, compile_asin, description="Bounded fixed-point arcsine.")
acos = BoundedOperation("acos", make_acos, compile_acos, description="Bounded fixed-point arccosine.")
atan = BoundedOperation("atan", make_atan, compile_atan, description="Bounded fixed-point arctangent.")
cbrt = BoundedOperation("cbrt", make_cbrt, compile_cbrt, description="Bounded fixed-point cube root.")
degrees = BoundedOperation(
    "degrees",
    make_degrees,
    compile_degrees,
    description="Bounded fixed-point radians-to-degrees conversion.",
)
radians = BoundedOperation(
    "radians",
    make_radians,
    compile_radians,
    description="Bounded fixed-point degrees-to-radians conversion.",
)
exp = BoundedOperation("exp", make_exp, compile_exp, description="Bounded fixed-point exponential.")
expm1 = BoundedOperation(
    "expm1",
    make_expm1,
    compile_expm1,
    description="Bounded fixed-point exp(x) - 1.",
)
log = BoundedOperation(
    "log",
    make_log,
    compile_log,
    description="Bounded fixed-point natural logarithm.",
)
log1p = BoundedOperation(
    "log1p",
    make_log1p,
    compile_log1p,
    description="Bounded fixed-point log(1 + x).",
)
log2 = BoundedOperation(
    "log2",
    make_log2,
    compile_log2,
    description="Bounded fixed-point base-2 logarithm.",
)
log10 = BoundedOperation(
    "log10",
    make_log10,
    compile_log10,
    description="Bounded fixed-point base-10 logarithm.",
)
sqrt = BoundedOperation(
    "sqrt",
    make_sqrt,
    compile_sqrt,
    description="Bounded fixed-point square root.",
)
erf = BoundedOperation("erf", make_erf, compile_erf, description="Bounded fixed-point erf.")
erfc = BoundedOperation("erfc", make_erfc, compile_erfc, description="Bounded fixed-point erfc.")
tanh = BoundedOperation("tanh", make_tanh, compile_tanh, description="Bounded fixed-point tanh.")
sinh = BoundedOperation("sinh", make_sinh, compile_sinh, description="Bounded fixed-point sinh.")
cosh = BoundedOperation("cosh", make_cosh, compile_cosh, description="Bounded fixed-point cosh.")
sigmoid = BoundedOperation(
    "sigmoid",
    make_sigmoid,
    compile_sigmoid,
    description="Bounded fixed-point sigmoid.",
)

unsigned_floor_divide = BoundedOperation(
    "unsigned_floor_divide",
    make_unsigned_floor_divide,
    compile_unsigned_floor_divide,
    description="Unsigned bit-level floor division.",
)
fixed_point_divide = BoundedOperation(
    "fixed_point_divide",
    make_fixed_point_divide,
    compile_fixed_point_divide,
    description="Unsigned bit-level fixed-point division.",
)


copysign = BoundedOperation(
    "copysign",
    make_copysign,
    compile_copysign,
    description="Bounded encrypted copysign(x, y).",
)
saturating_add = BoundedOperation(
    "saturating_add",
    make_saturating_add,
    compile_saturating_add,
    description="Bounded encrypted addition clamped back into the input range.",
)
saturating_subtract = BoundedOperation(
    "saturating_subtract",
    make_saturating_subtract,
    compile_saturating_subtract,
    description="Bounded encrypted subtraction clamped back into the input range.",
)
saturating_multiply = BoundedOperation(
    "saturating_multiply",
    make_saturating_multiply,
    compile_saturating_multiply,
    description="Bounded encrypted multiplication clamped back into the input range.",
)
round_to_multiple = BoundedOperation(
    "round_to_multiple",
    make_round_to_multiple,
    compile_round_to_multiple,
    description="Bounded quantization to the nearest multiple of a public step.",
)
modf = BoundedOperation(
    "modf",
    make_modf,
    compile_modf,
    description="Bounded fixed-point (fractional, integer) decomposition.",
)
fixed_point_multiply = BoundedOperation(
    "fixed_point_multiply",
    make_fixed_point_multiply,
    compile_fixed_point_multiply,
    description="Rescaled multiplication of two fixed-point encrypted values.",
)
atan2 = BoundedOperation(
    "atan2",
    make_atan2,
    compile_atan2,
    description="Bounded fixed-point quadrant-aware arctangent.",
)
gamma = BoundedOperation(
    "gamma",
    make_gamma,
    compile_gamma,
    description="Bounded fixed-point gamma function.",
)
lgamma = BoundedOperation(
    "lgamma",
    make_lgamma,
    compile_lgamma,
    description="Bounded fixed-point log-gamma function.",
)
powmod = BoundedOperation(
    "powmod",
    make_powmod,
    compile_powmod,
    description="Public-base modular exponentiation with an encrypted exponent.",
)
unsigned_mod = BoundedOperation(
    "unsigned_mod",
    make_unsigned_mod,
    compile_unsigned_mod,
    description="Unsigned bit-level modulo from the restoring divider.",
)


asinh = BoundedOperation(
    "asinh",
    make_asinh,
    compile_asinh,
    description="Bounded fixed-point inverse hyperbolic sine.",
)
acosh = BoundedOperation(
    "acosh",
    make_acosh,
    compile_acosh,
    description="Bounded fixed-point inverse hyperbolic cosine.",
)
atanh = BoundedOperation(
    "atanh",
    make_atanh,
    compile_atanh,
    description="Bounded fixed-point inverse hyperbolic tangent.",
)
exp2 = BoundedOperation(
    "exp2",
    make_exp2,
    compile_exp2,
    description="Bounded fixed-point base-2 exponential.",
)
fdim = BoundedOperation(
    "fdim",
    make_fdim,
    compile_fdim,
    description="Bounded encrypted positive difference max(x - y, 0).",
)
remainder = BoundedOperation(
    "remainder",
    make_remainder,
    compile_remainder,
    description="Bounded IEEE-style remainder with ties-to-even quotient rounding.",
)
ilogb = BoundedOperation(
    "ilogb",
    make_ilogb,
    compile_ilogb,
    description="Bounded floor(log2(|x|)) with explicit zero behavior.",
)
ldexp = BoundedOperation(
    "ldexp",
    make_ldexp,
    compile_ldexp,
    description="Multiplication by a public power of two.",
)
scalbn = ldexp

# C-math-parity aliases for existing operations.
tgamma = gamma
fabs = absolute
fmax = maximum
fmin = minimum

__all__ = [
    "abs",
    "abs_diff",
    "absolute",
    "acos",
    "acosh",
    "add",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "band",
    "bit_and",
    "BIT_AND_LUT",
    "bit_and_many",
    "bit_length_bits",
    "bit_not",
    "BIT_NOT_LUT",
    "bit_op_many",
    "bit_or",
    "BIT_OR_LUT",
    "bit_or_many",
    "bit_select",
    "BIT_SELECT_LUT",
    "bit_xor",
    "BIT_XOR_LUT",
    "bit_xor_many",
    "bits_to_unsigned",
    "bnot",
    "bor",
    "BoundedOperation",
    "bsel",
    "bxor",
    "cbrt",
    "ceil",
    "clamp",
    "comb",
    "combinations",
    "compile_abs",
    "compile_abs_diff",
    "compile_absolute",
    "compile_acos",
    "compile_acosh",
    "compile_add",
    "compile_asin",
    "compile_asinh",
    "compile_atan",
    "compile_atan2",
    "compile_atanh",
    "compile_cbrt",
    "compile_ceil",
    "compile_clamp",
    "compile_comb",
    "compile_combinations",
    "compile_copysign",
    "compile_cos",
    "compile_cosh",
    "compile_cube",
    "compile_degrees",
    "compile_divmod",
    "compile_equal",
    "compile_erf",
    "compile_erfc",
    "compile_exp",
    "compile_exp2",
    "compile_expm1",
    "compile_exponential",
    "compile_factorial",
    "compile_fdim",
    "compile_fibonacci",
    "compile_fixed_point_divide",
    "compile_fixed_point_multiply",
    "compile_floor",
    "compile_floor_ceil",
    "compile_fma",
    "compile_gamma",
    "compile_gcd",
    "compile_greater",
    "compile_greater_equal",
    "compile_hypot",
    "compile_ilogb",
    "compile_is_close",
    "compile_is_coprime",
    "compile_is_divisible",
    "compile_is_even",
    "compile_is_odd",
    "compile_is_prime",
    "compile_is_zero",
    "compile_isqrt",
    "compile_lcm",
    "compile_ldexp",
    "compile_less",
    "compile_less_equal",
    "compile_lgamma",
    "compile_log",
    "compile_log10",
    "compile_log1p",
    "compile_log2",
    "compile_maximum",
    "compile_minimum",
    "compile_mod_inverse",
    "compile_modf",
    "compile_modulo",
    "compile_multiply",
    "compile_negate",
    "compile_next_prime",
    "compile_not_equal",
    "compile_perm",
    "compile_permutations",
    "compile_power",
    "compile_powmod",
    "compile_radians",
    "compile_remainder",
    "compile_rescale",
    "compile_round",
    "compile_round_to_multiple",
    "compile_saturating_add",
    "compile_saturating_multiply",
    "compile_saturating_subtract",
    "compile_scalar_mul",
    "compile_scalar_multiply",
    "compile_scalbn",
    "compile_select",
    "compile_sigmoid",
    "compile_sin",
    "compile_sinh",
    "compile_sqrt",
    "compile_square",
    "compile_sub",
    "compile_subtract",
    "compile_tan",
    "compile_tanh",
    "compile_totient",
    "compile_trunc",
    "compile_unsigned_floor_divide",
    "compile_unsigned_mod",
    "copysign",
    "cos",
    "cosh",
    "cube",
    "decode_fixed_point",
    "degrees",
    "divmod",
    "encode_fixed_point",
    "equal",
    "erf",
    "erfc",
    "estimate_lookup_cost",
    "exp",
    "exp2",
    "expm1",
    "fabs",
    "factorial",
    "fadd_bit",
    "fdim",
    "FHECostWarning",
    "fibonacci",
    "fixed_point_divide",
    "fixed_point_divide_bits",
    "fixed_point_multiply",
    "floor",
    "floor_ceil",
    "fma",
    "fmax",
    "fmin",
    "fsub_bit",
    "full_adder_bit",
    "FULL_ADDER_CARRY_LUT",
    "FULL_ADDER_SUM_LUT",
    "full_subtractor_bit",
    "FULL_SUBTRACTOR_BORROW_LUT",
    "FULL_SUBTRACTOR_DIFF_LUT",
    "gamma",
    "gcd",
    "greater",
    "greater_equal",
    "hypot",
    "ilogb",
    "integer_to_bits",
    "is_close",
    "is_coprime",
    "is_divisible",
    "is_even",
    "is_odd",
    "is_prime",
    "is_zero",
    "isqrt",
    "lcm",
    "ldexp",
    "less",
    "less_equal",
    "lgamma",
    "log",
    "log10",
    "log1p",
    "log2",
    "LookupCost",
    "LookupResourceError",
    "make_abs",
    "make_abs_diff",
    "make_absolute",
    "make_acos",
    "make_acosh",
    "make_asin",
    "make_asinh",
    "make_atan",
    "make_atan2",
    "make_atanh",
    "make_cbrt",
    "make_ceil",
    "make_clamp",
    "make_comb",
    "make_combinations",
    "make_copysign",
    "make_cos",
    "make_cosh",
    "make_degrees",
    "make_divmod",
    "make_erf",
    "make_erfc",
    "make_exp",
    "make_exp2",
    "make_expm1",
    "make_exponential",
    "make_factorial",
    "make_fdim",
    "make_fibonacci",
    "make_fixed_point_divide",
    "make_fixed_point_multiply",
    "make_floor",
    "make_floor_ceil",
    "make_gamma",
    "make_gcd",
    "make_hypot",
    "make_ilogb",
    "make_is_close",
    "make_is_coprime",
    "make_is_divisible",
    "make_is_even",
    "make_is_odd",
    "make_is_prime",
    "make_isqrt",
    "make_lcm",
    "make_ldexp",
    "make_lgamma",
    "make_log",
    "make_log10",
    "make_log1p",
    "make_log2",
    "make_mod_inverse",
    "make_modf",
    "make_modulo",
    "make_next_prime",
    "make_perm",
    "make_permutations",
    "make_power",
    "make_powmod",
    "make_radians",
    "make_remainder",
    "make_rescale",
    "make_round",
    "make_round_to_multiple",
    "make_saturating_add",
    "make_saturating_multiply",
    "make_saturating_subtract",
    "make_scalar_multiply",
    "make_scalbn",
    "make_sigmoid",
    "make_sin",
    "make_sinh",
    "make_sqrt",
    "make_tan",
    "make_tanh",
    "make_totient",
    "make_trunc",
    "make_unsigned_floor_divide",
    "make_unsigned_mod",
    "maximum",
    "minimum",
    "mod_inverse",
    "modf",
    "modulo",
    "multiply",
    "multiply_bits",
    "negate",
    "next_prime",
    "not_equal",
    "parity_bits",
    "perm",
    "permutations",
    "popcount_bits",
    "power",
    "powmod",
    "radians",
    "remainder",
    "rescale",
    "rotate_left_bits",
    "rotate_right_bits",
    "round",
    "round_to_multiple",
    "saturating_add",
    "saturating_multiply",
    "saturating_subtract",
    "scalbn",
    "select",
    "shift_left_bits",
    "shift_right_bits",
    "sigmoid",
    "sign_magnitude_to_twos_complement_bits",
    "sin",
    "sinh",
    "sqrt",
    "square",
    "subtract",
    "tan",
    "tanh",
    "tgamma",
    "totient",
    "trunc",
    "twos_complement_add_bits",
    "twos_complement_bits",
    "twos_complement_multiply_by_constant_bits",
    "unsigned_compare_bits",
    "unsigned_divide_bits",
    "unsigned_floor_divide",
    "unsigned_mod",
    "unsigned_mod_bits",
    "unsigned_to_bits",
]
