"""Math-style helpers for Concrete FHE circuits.

The functions in this subpackage use bounded integer domains. Some operations
compile as native Concrete arithmetic, while others use lookup tables over the
declared domain.
"""

from ._lookup import FHECostWarning, LookupCost, LookupResourceError, estimate_lookup_cost
from ._operation import BoundedOperation
from .basic import (
    add,
    compile_abs,
    compile_absolute,
    compile_add,
    compile_clamp,
    compile_divmod,
    compile_equal,
    compile_greater,
    compile_greater_equal,
    compile_is_close,
    compile_less,
    compile_less_equal,
    compile_modulo,
    compile_multiply,
    compile_negate,
    compile_not_equal,
    compile_scalar_mul,
    compile_scalar_multiply,
    compile_square,
    compile_sub,
    compile_subtract,
    equal,
    greater,
    greater_equal,
    less,
    less_equal,
    make_abs,
    make_absolute,
    make_clamp,
    make_divmod,
    make_is_close,
    make_modulo,
    make_scalar_multiply,
    multiply,
    negate,
    not_equal,
    square,
    subtract,
)
from .binary_division import (
    compile_fixed_point_divide,
    compile_unsigned_floor_divide,
    fixed_point_divide_bits,
    make_fixed_point_divide,
    make_unsigned_floor_divide,
    unsigned_divide_bits,
)
from .bits import (
    BIT_AND_LUT,
    BIT_NOT_LUT,
    BIT_OR_LUT,
    BIT_SELECT_LUT,
    BIT_XOR_LUT,
    FULL_ADDER_CARRY_LUT,
    FULL_ADDER_SUM_LUT,
    FULL_SUBTRACTOR_BORROW_LUT,
    FULL_SUBTRACTOR_DIFF_LUT,
    band,
    bit_and,
    bit_not,
    bit_or,
    bit_or_many,
    bit_select,
    bit_xor,
    bits_to_unsigned,
    bnot,
    bor,
    bsel,
    bxor,
    fadd_bit,
    fsub_bit,
    full_adder_bit,
    full_subtractor_bit,
    integer_to_bits,
    multiply_bits,
    sign_magnitude_to_twos_complement_bits,
    twos_complement_add_bits,
    twos_complement_bits,
    twos_complement_multiply_by_constant_bits,
    unsigned_to_bits,  
)
from .combinatorics import (
    compile_comb,
    compile_combinations,
    compile_exponential,
    compile_factorial,
    compile_fibonacci,
    compile_perm,
    compile_permutations,
    compile_power,
    make_comb,
    make_combinations,
    make_exponential,
    make_factorial,
    make_fibonacci,
    make_perm,
    make_permutations,
    make_power,
)
from .fixed_point import (
    compile_ceil,
    compile_floor,
    compile_floor_ceil,
    compile_rescale,
    compile_round,
    compile_trunc,
    make_ceil,
    make_floor,
    make_floor_ceil,
    make_rescale,
    make_round,
    make_trunc,
)
from .number_theory import (
    compile_gcd,
    compile_is_coprime,
    compile_is_divisible,
    compile_is_even,
    compile_is_odd,
    compile_is_prime,
    compile_isqrt,
    compile_lcm,
    make_gcd,
    make_is_coprime,
    make_is_divisible,
    make_is_even,
    make_is_odd,
    make_is_prime,
    make_isqrt,
    make_lcm,
)
from .special import (
    compile_cos,
    compile_cosh,
    compile_erf,
    compile_erfc,
    compile_exp,
    compile_expm1,
    compile_log,
    compile_log1p,
    compile_log2,
    compile_log10,
    compile_sigmoid,
    compile_sin,
    compile_sinh,
    compile_sqrt,
    compile_tan,
    compile_tanh,
    make_cos,
    make_cosh,
    make_erf,
    make_erfc,
    make_exp,
    make_expm1,
    make_log,
    make_log1p,
    make_log2,
    make_log10,
    make_sigmoid,
    make_sin,
    make_sinh,
    make_sqrt,
    make_tan,
    make_tanh,
)

absolute = BoundedOperation(
    "absolute",
    make_absolute,
    compile_absolute,
    description="Bounded encrypted absolute value.",
)
abs = absolute
clamp = BoundedOperation(
    "clamp",
    make_clamp,
    compile_clamp,
    description="Bounded encrypted clamp.",
)
modulo = BoundedOperation(
    "modulo",
    make_modulo,
    compile_modulo,
    description="Bounded encrypted modulo with explicit zero-denominator behavior.",
)
divmod = BoundedOperation(
    "divmod",
    make_divmod,
    compile_divmod,
    description="Bounded encrypted quotient and remainder.",
)
is_close = BoundedOperation(
    "is_close",
    make_is_close,
    compile_is_close,
    description="Bounded encrypted integer closeness predicate.",
)

factorial = BoundedOperation(
    "factorial",
    make_factorial,
    compile_factorial,
    description="Bounded encrypted factorial.",
)
fibonacci = BoundedOperation(
    "fibonacci",
    make_fibonacci,
    compile_fibonacci,
    description="Bounded encrypted Fibonacci sequence lookup.",
)
power = BoundedOperation(
    "power",
    make_power,
    compile_power,
    description="Public-base exponentiation with an encrypted exponent.",
)
comb = BoundedOperation(
    "comb",
    make_comb,
    compile_comb,
    description="Bounded encrypted combinations.",
)
combinations = comb
perm = BoundedOperation(
    "perm",
    make_perm,
    compile_perm,
    description="Bounded encrypted permutations.",
)
permutations = perm

gcd = BoundedOperation(
    "gcd",
    make_gcd,
    compile_gcd,
    description="Bounded encrypted greatest common divisor.",
)
lcm = BoundedOperation(
    "lcm",
    make_lcm,
    compile_lcm,
    description="Bounded encrypted least common multiple.",
)
is_coprime = BoundedOperation(
    "is_coprime",
    make_is_coprime,
    compile_is_coprime,
    description="Bounded encrypted coprime predicate.",
)
is_divisible = BoundedOperation(
    "is_divisible",
    make_is_divisible,
    compile_is_divisible,
    description="Bounded encrypted divisibility predicate.",
)
isqrt = BoundedOperation(
    "isqrt",
    make_isqrt,
    compile_isqrt,
    description="Bounded encrypted integer square root.",
)
is_even = BoundedOperation(
    "is_even",
    make_is_even,
    compile_is_even,
    description="Bounded encrypted even predicate.",
)
is_odd = BoundedOperation(
    "is_odd",
    make_is_odd,
    compile_is_odd,
    description="Bounded encrypted odd predicate.",
)
is_prime = BoundedOperation(
    "is_prime",
    make_is_prime,
    compile_is_prime,
    description="Bounded encrypted primality predicate.",
)

floor = BoundedOperation(
    "floor",
    make_floor,
    compile_floor,
    description="Bounded fixed-point floor.",
)
ceil = BoundedOperation(
    "ceil",
    make_ceil,
    compile_ceil,
    description="Bounded fixed-point ceil.",
)
trunc = BoundedOperation(
    "trunc",
    make_trunc,
    compile_trunc,
    description="Bounded fixed-point truncation toward zero.",
)
round = BoundedOperation(
    "round",
    make_round,
    compile_round,
    description="Bounded fixed-point rounding.",
)
floor_ceil = BoundedOperation(
    "floor_ceil",
    make_floor_ceil,
    compile_floor_ceil,
    description="Bounded fixed-point floor and ceil pair.",
)
rescale = BoundedOperation(
    "rescale",
    make_rescale,
    compile_rescale,
    description="Bounded fixed-point rescaling.",
)

sin = BoundedOperation("sin", make_sin, compile_sin, description="Bounded fixed-point sine.")
cos = BoundedOperation("cos", make_cos, compile_cos, description="Bounded fixed-point cosine.")
tan = BoundedOperation("tan", make_tan, compile_tan, description="Bounded fixed-point tangent.")
exp = BoundedOperation("exp", make_exp, compile_exp, description="Bounded fixed-point exponential.")
expm1 = BoundedOperation(
    "expm1",
    make_expm1,
    compile_expm1,
    description="Bounded fixed-point exp(x) - 1.",
)
log = BoundedOperation(
    "log",
    make_log,
    compile_log,
    description="Bounded fixed-point natural logarithm.",
)
log1p = BoundedOperation(
    "log1p",
    make_log1p,
    compile_log1p,
    description="Bounded fixed-point log(1 + x).",
)
log2 = BoundedOperation(
    "log2",
    make_log2,
    compile_log2,
    description="Bounded fixed-point base-2 logarithm.",
)
log10 = BoundedOperation(
    "log10",
    make_log10,
    compile_log10,
    description="Bounded fixed-point base-10 logarithm.",
)
sqrt = BoundedOperation(
    "sqrt",
    make_sqrt,
    compile_sqrt,
    description="Bounded fixed-point square root.",
)
erf = BoundedOperation("erf", make_erf, compile_erf, description="Bounded fixed-point erf.")
erfc = BoundedOperation("erfc", make_erfc, compile_erfc, description="Bounded fixed-point erfc.")
tanh = BoundedOperation("tanh", make_tanh, compile_tanh, description="Bounded fixed-point tanh.")
sinh = BoundedOperation("sinh", make_sinh, compile_sinh, description="Bounded fixed-point sinh.")
cosh = BoundedOperation("cosh", make_cosh, compile_cosh, description="Bounded fixed-point cosh.")
sigmoid = BoundedOperation(
    "sigmoid",
    make_sigmoid,
    compile_sigmoid,
    description="Bounded fixed-point sigmoid.",
)

unsigned_floor_divide = BoundedOperation(
    "unsigned_floor_divide",
    make_unsigned_floor_divide,
    compile_unsigned_floor_divide,
    description="Unsigned bit-level floor division.",
)
fixed_point_divide = BoundedOperation(
    "fixed_point_divide",
    make_fixed_point_divide,
    compile_fixed_point_divide,
    description="Unsigned bit-level fixed-point division.",
)

__all__ = [
    "BIT_AND_LUT",
    "BIT_NOT_LUT",
    "BIT_OR_LUT",
    "BIT_SELECT_LUT",
    "BIT_XOR_LUT",
    "BoundedOperation",
    "FHECostWarning",
    "FULL_ADDER_CARRY_LUT",
    "FULL_ADDER_SUM_LUT",
    "FULL_SUBTRACTOR_BORROW_LUT",
    "FULL_SUBTRACTOR_DIFF_LUT",
    "LookupCost",
    "LookupResourceError",
    "abs",
    "add",
    "absolute",
    "band",
    "bit_and",
    "bit_not",
    "bit_or",
    "bit_or_many",
    "bit_select",
    "bit_xor",
    "bits_to_unsigned",
    "bnot",
    "bor",
    "bsel",
    "bxor",
    "ceil",
    "clamp",
    "comb",
    "combinations",
    "compile_abs",
    "compile_absolute",
    "compile_add",
    "compile_ceil",
    "compile_clamp",
    "compile_comb",
    "compile_combinations",
    "compile_cos",
    "compile_cosh",
    "compile_divmod",
    "compile_equal",
    "compile_erf",
    "compile_erfc",
    "compile_exp",
    "compile_expm1",
    "compile_exponential",
    "compile_factorial",
    "compile_fixed_point_divide",
    "compile_fibonacci",
    "compile_floor",
    "compile_floor_ceil",
    "compile_gcd",
    "compile_greater",
    "compile_greater_equal",
    "compile_is_close",
    "compile_is_coprime",
    "compile_is_divisible",
    "compile_is_even",
    "compile_is_odd",
    "compile_is_prime",
    "compile_isqrt",
    "compile_lcm",
    "compile_less",
    "compile_less_equal",
    "compile_log",
    "compile_log1p",
    "compile_log2",
    "compile_log10",
    "compile_modulo",
    "compile_multiply",
    "compile_negate",
    "compile_not_equal",
    "compile_perm",
    "compile_permutations",
    "compile_power",
    "compile_rescale",
    "compile_round",
    "compile_scalar_mul",
    "compile_scalar_multiply",
    "compile_sigmoid",
    "compile_sin",
    "compile_sinh",
    "compile_sqrt",
    "compile_square",
    "compile_sub",
    "compile_subtract",
    "compile_tan",
    "compile_tanh",
    "compile_trunc",
    "compile_unsigned_floor_divide",
    "cos",
    "cosh",
    "divmod",
    "equal",
    "erf",
    "erfc",
    "estimate_lookup_cost",
    "exp",
    "expm1",
    "factorial",
    "fadd_bit",
    "fibonacci",
    "fixed_point_divide",
    "fixed_point_divide_bits",
    "floor",
    "floor_ceil",
    "fsub_bit",
    "full_adder_bit",
    "full_subtractor_bit",
    "gcd",
    "greater",
    "greater_equal",
    "integer_to_bits",
    "is_close",
    "is_coprime",
    "is_divisible",
    "is_even",
    "is_odd",
    "is_prime",
    "isqrt",
    "lcm",
    "less",
    "less_equal",
    "log",
    "log1p",
    "log2",
    "log10",
    "make_abs",
    "make_absolute",
    "make_ceil",
    "make_clamp",
    "make_comb",
    "make_combinations",
    "make_cos",
    "make_cosh",
    "make_divmod",
    "make_erf",
    "make_erfc",
    "make_exp",
    "make_expm1",
    "make_exponential",
    "make_factorial",
    "make_fixed_point_divide",
    "make_fibonacci",
    "make_floor",
    "make_floor_ceil",
    "make_gcd",
    "make_is_close",
    "make_is_coprime",
    "make_is_divisible",
    "make_is_even",
    "make_is_odd",
    "make_is_prime",
    "make_isqrt",
    "make_lcm",
    "make_log",
    "make_log1p",
    "make_log2",
    "make_log10",
    "make_modulo",
    "make_perm",
    "make_permutations",
    "make_power",
    "make_rescale",
    "make_round",
    "make_scalar_multiply",
    "make_sigmoid",
    "make_sin",
    "make_sinh",
    "make_sqrt",
    "make_tan",
    "make_tanh",
    "make_trunc",
    "make_unsigned_floor_divide",
    "modulo",
    "multiply_bits",
    "multiply",
    "negate",
    "not_equal",
    "perm",
    "permutations",
    "power",
    "rescale",
    "round",
    "sigmoid",
    "sign_magnitude_to_twos_complement_bits",
    "sin",
    "sinh",
    "sqrt",
    "square",
    "subtract",
    "tan",
    "tanh",
    "trunc",
    "twos_complement_add_bits",
    "twos_complement_bits",
    "twos_complement_multiply_by_constant_bits",
    "unsigned_divide_bits",
    "unsigned_floor_divide",
    "unsigned_to_bits",
]
