"""Bounded integer helpers for Concrete FHE."""

from . import math, ml
from .arithmetic import (
    compile_floor_divide,
    compile_floor_divide_by_product,
    compile_compare,
    compile_sign,
    make_floor_divide,
    make_floor_divide_by_product,
    compare,
    sign,
)
from .arrays import (
    array_add,
    array_all_equal,
    array_contains,
    array_count,
    array_multiply,
    array_pad,
    array_scale,
    array_slice,
    array_sub,
    array_sum,
    compile_argmax,
    compile_argmin,
    compile_compare_swap,
    compile_maximum,
    compile_minimum,
    compile_sort,
    make_argmax,
    make_argmin,
    make_compare_swap,
    make_maximum,
    make_minimum,
    make_sort,
)

__all__ = [
    "array_add",
    "array_all_equal",
    "array_contains",
    "array_count",
    "array_multiply",
    "array_pad",
    "array_scale",
    "array_slice",
    "array_sub",
    "array_sum",
    "compile_argmax",
    "compile_argmin",
    "compile_compare",
    "compile_compare_swap",
    "compile_floor_divide",
    "compile_floor_divide_by_product",
    "compile_maximum",
    "compile_minimum",
    "compile_sign",
    "compile_sort",
    "compare",
    "math",
    "make_argmax",
    "make_argmin",
    "make_compare_swap",
    "make_floor_divide",
    "make_floor_divide_by_product",
    "make_maximum",
    "make_minimum",
    "make_sort",
    "math",
    "ml",
    "sign",
]

__version__ = "0.2.2"
