"""Machine Learning specific operations for Concrete FHE."""

# sign, sigmoid, and tanh are re-exported from their real homes for
# backwards compatibility; sigmoid/tanh are BoundedOperation compile
# factories from the math subpackage, not traceable activations.
from ..arithmetic import sign
from ..math import sigmoid, tanh, make_sigmoid, compile_sigmoid
from .activations import (
    compile_leaky_relu,
    compile_relu,
    compile_threshold_activation,
    compile_unit_step,
    leaky_relu,
    relu,
    threshold_activation,
    unit_step,
    make_softmax,
    compile_softmax,
)
from .core import (
    accuracy_score,
    compile_hinge_loss,
    confusion_matrix,
    make_cross_entropy_loss,
    compile_cross_entropy_loss,
    euclidean_distance_squared,
    f1_score,
    false_negatives,
    false_positives,
    hamming_distance,
    hinge_loss,
    manhattan_distance,
    mean_absolute_error,
    mean_squared_error,
    precision_score,
    recall_score,
    true_negatives,
    true_positives,
    l1_norm,
)
from .matrix import dot_product, matrix_add, matrix_transpose, matrix_subtract, matrix_multiply, matrix_vector_multiply, tensor_flatten, matrix_elementwise_multiply, matrix_exp, covariance_matrix
from .models import (
    argmax_inference,
    cnn_inference,
    compile_decision_tree_node,
    decision_tree_inference,
    decision_tree_node,
    knn_inference,
    linear_regression_inference,
    logistic_regression_inference,
    majority_votes,
    mlp_inference,
    naive_bayes_inference,
    nearest_centroid_inference,
    pca_inference,
    random_forest_inference,
    svm_inference,
    xgboost_inference,
    max_pooling_2d,
    avg_pooling_2d,
    auto_quantizer,
)
from .stats import array_max, array_mean, array_min, array_range, array_variance, array_count_greater
from .utils import binarize, one_hot_encode, clip_array, normalize_array
from .training import naive_bayes_training
from .classes import (
    FHEModel,
    FHELogisticRegression,
    FHELinearRegression,
    FHEDecisionTree,
    FHEPCA,
    FHECNN,
    FHERandomForest,
    FHEXGBoost,
    FHESVM,
    FHEKNN,
    FHEKMeans,
    FHENaiveBayes,
    FHENaiveBayesTrainer,
    FHEMLP,
)
from .core import r2_score
from .trainers import (
    FHEDecisionTreeTrainer,
    FHEKMeansTrainer,
    FHELinearRegressionTrainer,
    FHETrainer,
    linear_regression_training,
)
from . import classification, clustering, regression

__all__ = [
    "argmax_inference",
    "array_count_greater",
    "array_max",
    "array_mean",
    "array_min",
    "array_range",
    "array_variance",
    "accuracy_score",
    "cnn_inference",
    "f1_score",
    "mlp_inference",
    "naive_bayes_inference",
    "nearest_centroid_inference",
    "pca_inference",
    "precision_score",
    "random_forest_inference",
    "recall_score",
    "compile_decision_tree_node",
    "compile_hinge_loss",
    "compile_leaky_relu",
    "compile_relu",
    "compile_threshold_activation",
    "compile_unit_step",
    "compile_softmax",
    "compile_sigmoid",
    "make_softmax",
    "make_sigmoid",
    "confusion_matrix",
    "make_cross_entropy_loss",
    "compile_cross_entropy_loss",
    "dot_product",
    "euclidean_distance_squared",
    "false_negatives",
    "false_positives",
    "hamming_distance",
    "hinge_loss",
    "knn_inference",
    "leaky_relu",
    "linear_regression_inference",
    "logistic_regression_inference",
    "majority_votes",
    "decision_tree_inference",
    "decision_tree_node",
    "manhattan_distance",
    "matrix_add",
    "matrix_multiply",
    "matrix_subtract",
    "matrix_transpose",
    "matrix_vector_multiply",
    "mean_absolute_error",
    "mean_squared_error",
    "relu",
    "sigmoid",
    "sign",
    "svm_inference",
    "tanh",
    "threshold_activation",
    "true_negatives",
    "true_positives",
    "unit_step",
    "binarize",
    "clip_array",
    "one_hot_encode",
    "xgboost_inference",
    "max_pooling_2d",
    "avg_pooling_2d",
    "auto_quantizer",
    "normalize_array",
    "tensor_flatten",
    "l1_norm",
    "matrix_elementwise_multiply",
    "matrix_exp",
    "covariance_matrix",
    "naive_bayes_training",
    "linear_regression_training",
    "r2_score",
    "classification",
    "clustering",
    "regression",
    "FHETrainer",
    "FHEDecisionTreeTrainer",
    "FHEKMeans",
    "FHEKMeansTrainer",
    "FHELinearRegressionTrainer",
    "FHENaiveBayesTrainer",
    "FHEModel",
    "FHELogisticRegression",
    "FHELinearRegression",
    "FHEDecisionTree",
    "FHEPCA",
    "FHECNN",
    "FHERandomForest",
    "FHEXGBoost",
    "FHESVM",
    "FHEKNN",
    "FHENaiveBayes",
    "FHEMLP",
]
